name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag daansterckx/P4B2-api:latest
    - name: login docker hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: push to docker hub
      run: docker push daansterckx/P4B2-api:latest
