name: Trigger auto deployment for p4-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ bw-pipeline ]
    paths:
    - '**'
    - '.github/workflows/p4-api-AutoDeployTrigger-a12295f2-f209-4cd5-9d63-1dcda71e60f5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.P4API_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.P4API_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.P4API_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.P4API_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.P4API_REGISTRY_PASSWORD }}
          containerAppName: p4-api
          resourceGroup: p4-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


